VERBOSE = DEBUG
#
COL_NAME = SeqNr
COL_TTYPE= LONG
COL_HTYPE= INT
COL_COMM = "Running object number within the catalogue"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = Z_B
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "9-band BPZ redshift estimate; peak of posterior probability distribution"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = Z_B_MIN
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Lower bound of the 68% confidence interval of Z_B"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = Z_B_MAX
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Upper bound of the 68% confidence interval of Z_B"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = T_B
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Spectral type corresponding to Z_B"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = ODDS
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Empirical ODDS of Z_B"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = Z_ML
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "9-band BPZ maximum likelihood redshift"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = T_ML
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Spectral type corresponding to Z_ML"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = CHI_SQUARED_BPZ
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "chi sqared value associated with Z_B"
COL_UNIT = " "
COL_DEPTH=1
#
COL_NAME = M_0
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Reference magnitude for BPZ prior"
COL_UNIT = "mag"
COL_DEPTH=1
#
