COL_NAME = SeqNr 
COL_TTYPE = LONG
COL_HTYPE = INT
COL_COMM = "sequence number"
COL_UNIT = ""
COL_DEPTH = 1
#
COL_NAME = ALPHA_J2000
COL_TTYPE = DOUBLE
COL_HTYPE = FLOAT
COL_COMM = "Alpha"
COL_UNIT = "degrees"
COL_DEPTH = 1
#
COL_NAME = DELTA_J2000
COL_TTYPE = DOUBLE
COL_HTYPE = FLOAT
COL_COMM = "Delta"
COL_UNIT = "degrees"
COL_DEPTH = 1
#
COL_NAME = g
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "g magnitude"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = g_err
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "g magnitude error"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = r
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "r magnitude"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = r_err
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "r magnitude error"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = i
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "i magnitude"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = i_err
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "i magnitude error"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = z
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "z magnitude"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = z_err
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "z magnitude error"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = y
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "y magnitude"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = y_err
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "y magnitude error"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = rMeanKronMag
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "r magnitude Kron"
COL_UNIT = "PS mag"
COL_DEPTH = 1
#
COL_NAME = A_WORLD
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "semi major axis of object"
COL_UNIT = "degrees"
COL_DEPTH = 1
#
COL_NAME = B_WORLD
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "semi minor axis of object"
COL_UNIT = "degrees"
COL_DEPTH = 1
#
COL_NAME = THETA_J2000
COL_TTYPE = FLOAT
COL_HTYPE = FLOAT
COL_COMM = "object position ange"
COL_UNIT = "degrees"
COL_DEPTH = 1
#
COL_NAME = Flag
COL_TTYPE = SHORT
COL_HTYPE = INT
COL_COMM = "quality flag"
COL_UNIT = ""
COL_DEPTH = 1
