COL_NAME = Bflg_J
COL_TTYPE = SHORT
COL_HTYPE = INT
COL_COMM = "J flag"
COL_UNIT = ""
COL_DEPTH = 1
#
COL_NAME = Bflg_H
COL_TTYPE = SHORT
COL_HTYPE = INT
COL_COMM = "J flag"
COL_UNIT = ""
COL_DEPTH = 1
#
COL_NAME = Bflg_K
COL_TTYPE = SHORT
COL_HTYPE = INT
COL_COMM = "K flag"
COL_UNIT = ""
COL_DEPTH = 1
#

