VERBOSE = DEBUG
#
COL_NAME = SeqNr
COL_TTYPE= LONG
COL_HTYPE= INT
COL_COMM = "Running object number"
COL_UNIT = ""
COL_DEPTH=1
#
COL_NAME = X_IMAGE
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Object position along x"
COL_UNIT = "pixel"
COL_DEPTH=1
#
COL_NAME = Y_IMAGE
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Object position along y"
COL_UNIT = "pixel"
COL_DEPTH=1
#
COL_NAME = ALPHA_J2000
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Right ascension of barycenter (J2000)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = DELTA_J2000
COL_TTYPE= DOUBLE
COL_HTYPE= FLOAT
COL_COMM = "Declination of barycenter (J2000)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = MAG_AUTO
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Kron-like elliptical aperture magnitude"
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = MAGERR_AUTO
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "RMS error for AUTO magnitude"
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = MAG_BEST
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Best of MAG_AUTO and MAG_ISOCOR"
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = MAGERR_BEST
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "RMS error for MAG_BEST"
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = MAG_APER
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Fixed aperture magnitude vector"
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = MAGERR_APER
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "RMS error vector for fixed aperture mag."
COL_UNIT = "mag"
COL_DEPTH=1
#
COL_NAME = A_WORLD
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Profile RMS along major axis (world units)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = ERRA_WORLD
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "World RMS position error along major axis"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = B_WORLD
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Profile RMS along minor axis (world units)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = ERRB_WORLD
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "World RMS position error along minor axis"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = THETA_J2000
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Position angle (east of north) (J2000)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = ERRTHETA_J2000
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "J2000 error ellipse pos. angle (east of north)"
COL_UNIT = "deg"
COL_DEPTH=1
#
COL_NAME = ISOAREA_IMAGE
COL_TTYPE= LONG
COL_HTYPE= INT
COL_COMM = "Isophotal area above Analysis threshold"
COL_UNIT = "pixel**2"
COL_DEPTH=1
#
COL_NAME = MU_MAX
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Peak surface brightness above background"
COL_UNIT = "mag * arcsec**(-2)"
COL_DEPTH=1
#
COL_NAME = FLUX_RADIUS
COL_TTYPE= FLOAT
COL_HTYPE= FLOAT
COL_COMM = "Fraction-of-light radii"
COL_UNIT = "pixel"
COL_DEPTH=1
#
COL_NAME = Flag
COL_TTYPE= SHORT
COL_HTYPE= INT
COL_COMM = "Extraction flags"
COL_UNIT = ""
COL_DEPTH=1
#
