##################################
# Masking configuration file for
# CFHTLS Wide i-band data
# CONSERVATIVE -> Mask only things which REALLY have to be masked 
# (might miss some)
##################################

# include the THELI progs.ini file:
. /arc/home/hendrik/PhotoPipeTest/INSTALL/theli-1.30.0/scripts/Linux_64/progs.ini

# Directory containing the masking code:

MASKCONF=/arc/home/hendrik/src/automask/config/

#########################################################

# General settings

# Delete intermediate file:
CLEAN=1

########################################################

# Masking parameters for star masks

# Box side length for catalog download (arcmin)
# changed 12.04.08: now BOXSIZE specifies the search aperture radius
# in arcmin
BOXSIZE=50

# First do the "tight" masks for the diffraction spikes and bright haloes

DO_TIGHT_MASK=1

MAX_MAG_STARS_TIGHT_GSC1='16'     # for flagging preselection 14.5
MAX_MAG_STARS_TIGHT_GSC2='17.5'   # for flagging preselection 17.5
                                  # Make this limit seeing dependent?
APPLY_SEEING_DEP_GSC2_MAG_LIMIT=0 # if 1: use MAX_MAG_STARS_TIGHT_GSC2 
                                  # for SEEING=GSC2_MAG_LIMIT_REFSEEING
SEEING_DEP_GSC2_MAG_LIMIT_REFSEEING=0.8
SEEING_KEY='IQFINAL'               # fits key in image header giving the seeing value
SEEING_DEP_GSC2_MAG_LIMIT_CONVERSION=2.5
            # DeltaMag correction: 
            #-SEEING_DEP_GSC2_MAG_LIMIT_CONVERSION*lg(SEEING/GSC2_MAG_LIMIT_REFSEEING)
            # You might argue that 
            # SEEING_DEP_GSC2_MAG_LIMIT_CONVERSION=5, but I think that for diffraction
            # spikes only the compression along one direction is relevant
            # -> SEEING_DEP_GSC2_MAG_LIMIT_CONVERSION=2.5

MASK_KEY_TIGHT='maskgsct'

# Parameters for region sizes: mag, r_halo, r_diff_spikes, d_diff_spikes
STAR_REGION_PARAMETERS_TIGHT='
19.0 15 30 8
18.0 20 40 8
17.0 30 70 10
16.0 50 120 20
14.0 90 230 30
12.0 175 500 35
10.0 320 800 40
8.0 500 1600 40
6.0  1400 2800 50
5 1600 6000 150
0 3000 10000 200
'
OFFSET_TIGHT=0


MASK_AGRESSIVELY_TIGHT=1         # if 1: in GSC1 also objects marked as 
                                 # "non-stars" are flagged:
MASK_AGRESSIVELY_TIGHT_BRIGHT=0  # for mag<MASK_AGRESSIVELY_TIGHT_BRIGHT_MAGLIM
MASK_AGRESSIVELY_TIGHT_BRIGHT_MAGLIM=12 
MASK_AGRESSIVELY_WIDE=1          # Advantage: You get all stars
                                 # Disadvantage: Also some galaxies and 
                                 # spurious regions are masked

# Also do "wide" masks for the huge halos around very bright stars

DO_WIDE_MASK=1
MAX_MAG_STARS_WIDE='10.35'
STAR_REGION_PARAMETERS_WIDE='
10.35 1200 1200 10
8.0 1350 1350 40
6.0 1420 1420 50
5.0 1600 1600 50
0 3000 3000 200
'
MASK_KEY_WIDE='maskgscw'

DO_WIDE_MASK2=1
MAX_MAG_STARS_WIDE2='11.0'
STAR_REGION_PARAMETERS_WIDE2='
11.0 1200 1200 10
10.0 1210 1210 10
8.0 1360 1360 40
6.0 1430 1430 50
5.0 1610 1610 50
0 3010 3010 200
'
MASK_KEY_WIDE2='maskgscw2'


WIDE_MASK_ONLY_WITH_GSC1=1

# very important factor: positions relative to image center are modified by a 
# factor (1+OFFSET_TIGHT)
OFFSET_WIDE=-0.022

#### Currently not used / fully implemented:
# create own SExtractor catalog for star masking / checks
STAR_MASK_RUN_SEX=0
# SExtractor parameters
STAR_MIN_AREA=100
STAR_MIN_THRESH=50
STAR_DEBLEND_NTHRESH=32
STAR_DEBLEND_MINCONT=0.01
STAR_FILTER=gauss_3.0_5x5.conv
STAR_PARAM_FILE='mask_stars_sex.param'
# Interpolation across bad pixels 
# (VERY important, but doesn't really work, bright stars still split)
STAR_INTERP_MAXXLAG=512
STAR_INTERP_MAXYLAG=512


##########################################################
#
# Parameters for asteroid masking

ASTEROID_NEW_SEX_RUN=1 # 1: A new sextractor catalog will 
                       # be created with parameters below
                       # 0: Use an exisiting ldac catalog 
                       # as input (must be passed to script)

ASTEROID_EXCLUDE_MASKED_AREA=1 # If =1 objects which lie within a 
                               # pre-exisiting region mask file 
	                       # (must be passed) will be ignored


# Sextractor detection + debleinding parameters

ASTEROID_MIN_AREA=5
ASTEROID_MIN_THRESH=0.9
ASTEROID_FILTER=gauss_3.0_5x5.conv

ASTEROID_DEBLEND_NTHRESH=64	
ASTEROID_DEBLEND_MINCONT=0.0000001	

ASTEROID_PARAM_FILE='maskasteroids_sex.param'

# Table of catalog (only relevant if ASTEROID_NEW_SEX_RUN=0)
ASTEROID_TABLE=OBJECTS

# Keys in catalog
Xpos=Xpos
Ypos=Ypos
A=A
B=B
Theta=Theta


# Parameters for mask_asteroids.pl:
ASTEROID_TRANSVERSETOL=0.35 # Allowed position offset from line (alternative: 0.4)
ASTEROID_BOXBINNING=5       # rebinning width
ASTEROID_REGIONWIDTH=45     # transversal width of created regions
ASTEROID_REGIONSCALE=2.4    # Longitudinal stretching factor for regions


ASTEROID_NUMBER_ITERATIONS=4  # so many different parameter
                              # combinations are run and merged The
                              # following parameters contain
                              # ASTEROID_NUMBER_ITERATIONS options

# Size of starting box (linear patterns will be searched in areas of (ASTEROID_BOXSIZE*ASTEROID_BOXBINNING)^2)
ASTEROID_BOXSIZE_ALL='10 18 30 40' # Size of starting box (linear
                                   # patterns will be searched in
                                   # areas of
                                   # (ASTEROID_BOXSIZE*ASTEROID_BOXBINNING)^2)
                                   # (alternatives: 20 35)

ASTEROID_NMATCH_ALL='4 4 5 5'      # Min. number of matches on a line to be
                                   # considered

ASTEROID_MEDETHRESH_ALL='0.24 0.26 0.24 0.26' #  Min. value for
                                   # sqrt(median(e1)^2+median(e2)^2) #
                                   # Used to suppress galaxy chance
                                   # alignments


ASTEROID_MAXFRACSPURIOUS_ALL='0.9 0.9 0.9 0.9' # Maximum fraction of
                                               # accepted spurious
                                               # detections (except:
                                               # only spurious):
                                               # useful to suppress a
                                               # large number of
                                               # spurious detections
                                               # in case of
                                               # inadequately chosen
                                               # parameters. If above
                                               # the threshold: script
                                               # will reiterate with
                                               # the same
                                               # ASTEROID_BOXSIZE but
                                               # ASTEROID_NMATCH++

MASK_KEY_ASTEROID='maskast' # number will be attached



###
# END OF FILE
