# mm is maximum shapelet order that will be used
# mmpix is maximum size of a fits image that can be analyzed (mmpix x mmpix)
# mmpoly is maximum polynomial order to be used for spatial variation of PSF
#
# Make sure the following derived parameters are consistent with these choices
# msh = (mm+1) * (mm+2) /2 +2
# mmpoly2=(mmpoly+1)*(mmpoly+2)/2
#
flg1 = -Dmm=16 -Dmsh=155 -Dmmpix=4100 -Dmmcat=100000 -Dmmpoly=4 -Dmmpoly2=15
flg2 = -ffixed-line-length-0 -O -Wall
#
#LINUX LIBRARIES
libs = -L. -lshape -lutil -L/usr/X11R6/lib -lX11 -L ~/lib -lpgplot -lcfitsio -O
#
# OLD LIBRARIES:
#libs = -L. -lshape -lutil -L/usr/X11R6/lib -lX11 /home/strw/kuijken/lib/pgplot/libpgplot.a -lcfitsio -O
#libs = -L. -lshape -lutil -L/usr/X11R6/lib -L/usr/lib -lX11 -lpgplot -lpng -lcfitsio -O
#
# MAC LIBRARIES
#MACLIB: 
#libs = -L. -lshape -lutil -L/usr/X11R6/lib -lX11 -Wl,-framework -Wl,Foundation -lpgplot -L/home/strw/kuijken/lib -lcfitsio -L/sw/lib -lpng -lz -laquaterm -L/usr/lib -lgcc -O
#
#
.F.o: 
	f77 $(flg1) $(flg2) -c  $*.F


libshape.a: code.o convolve.o fitshear.o operators.o plotshape.o \
            setpsfmat.o setroundshear.o setroundshearshift.o
	ar crs libshape.a code.o convolve.o fitshear.o operators.o plotshape.o\
            setpsfmat.o setroundshear.o setroundshearshift.o
libutil.a: fits.o mrq.o workhorse.o fitpoly.o readpars.o
	ar crs libutil.a fits.o mrq.o workhorse.o fitpoly.o readpars.o

testmain: testmain.o libshape.a libutil.a
	f77 testmain.o $(libs) -o testmain
testshear: testshear.o  libshape.a libutil.a
	f77 testshear.o $(libs) -o testshear
testdecode: testdecode.o  libshape.a libutil.a
	f77 testdecode.o $(libs) -o testdecode
testortho: testortho.o  libshape.a libutil.a
	f77 testortho.o $(libs) -o testortho
testoper: testoper.o  libshape.a libutil.a
	f77 testoper.o $(libs) -o testoper
testconvolve: testconvolve.o  libshape.a libutil.a
	f77  testconvolve.o $(libs) -o testconvolve
testround: testround.o  libshape.a libutil.a
	f77 testround.o $(libs) -o testround
testplot: testplot.o  libshape.a libutil.a
	f77  testplot.o $(libs) -o testplot
testgaussians: testgaussians.o  libshape.a libutil.a
	f77 testgaussians.o $(libs) -o testgaussians
testmrq: testmrq.o libshape.a libutil.a
	f77 testmrq.o $(libs) -o testmrq
testpsfmat: testpsfmat.o  libshape.a libutil.a
	f77 testpsfmat.o $(libs) -o testpsfmat
testfitshear: testfitshear.o  libshape.a libutil.a
	f77 testfitshear.o $(libs) -o testfitshear
testfitshearmoffat: testfitshearmoffat.o  libshape.a libutil.a
	f77 testfitshearmoffat.o $(libs) -o testfitshearmoffat
thetest: thetest.o  libshape.a libutil.a
	f77 thetest.o $(libs) -o thetest
testreal: testreal.o  libshape.a libutil.a
	f77 testreal.o $(libs) -o testreal
testfits: testfits.o libshape.a libutil.a
	f77 testfits.o $(libs) -o testfits
testsherr: testsherr.o libshape.a libutil.a
	f77 testsherr.o $(libs) -o testsherr
testcentershape: testcentershape.o libshape.a libutil.a
	f77 testcentershape.o $(libs) -o testcentershape
testresiduals: testresiduals.o libshape.a libutil.a
	f77 testresiduals.o $(libs) -o testresiduals
testresiduals012: testresiduals012.o libshape.a libutil.a
	f77 testresiduals012.o $(libs) -o testresiduals012
testresiduals012conv: testresiduals012conv.o libshape.a libutil.a
	f77 testresiduals012conv.o $(libs) -o testresiduals012conv
testresiduals012mc: testresiduals012mc.o libshape.a libutil.a
	f77 testresiduals012mc.o $(libs) -o testresiduals012mc
testresiduals012_o2_mc: testresiduals012_o2_mc.o libshape.a libutil.a
	f77 testresiduals012_o2_mc.o $(libs) -o testresiduals012_o2_mc
testresiduals012_o3_mc: testresiduals012_o3_mc.o libshape.a libutil.a
	f77 testresiduals012_o3_mc.o $(libs) -o testresiduals012_o3_mc
testresiduals012mcnoise: testresiduals012mcnoise.o libshape.a libutil.a
	f77 testresiduals012mcnoise.o $(libs) -o testresiduals012mcnoise
test012: test012.o libshape.a libutil.a
	f77 test012.o  $(libs) -o test012
testfitmc: testfitmc.o libshape.a libutil.a
	f77 testfitmc.o $(libs) -o testfitmc 
testphotmc: testphotmc.o libshape.a libutil.a
	f77 testphotmc.o $(libs) -o testphotmc 
testsersic: testsersic.o libshape.a libutil.a
	f77 testsersic.o  $(libs) -o testsersic
testpsfcorphot: testpsfcorphot.o psfcorphot.o libshape.a libutil.a
	f77 testpsfcorphot.o psfcorphot.o $(libs) -o testpsfcorphot
testpsfcorphot_mc: testpsfcorphot_mc.o psfcorphot.o libshape.a libutil.a
	f77 testpsfcorphot_mc.o psfcorphot.o $(libs) -o testpsfcorphot_mc
testpsfcorphot_mc_no13: testpsfcorphot_mc_no13.o psfcorphot.o libshape.a libutil.a
	f77 testpsfcorphot_mc_no13.o psfcorphot.o $(libs) -o testpsfcorphot_mc_no13

fakeimage: fakeimage.o libshape.a libutil.a
	f77 fakeimage.o $(libs) -o fakeimage
fakeimage2: fakeimage2.o libshape.a libutil.a
	f77 fakeimage2.o $(libs) -o fakeimage2
fakeimage3: fakeimage3.o libshape.a libutil.a
	f77 fakeimage3.o $(libs) -o fakeimage3
fakeimage4: fakeimage4.o libshape.a libutil.a
	f77 fakeimage4.o $(libs) -o fakeimage4
fracpower: fracpower.o libshape.a libutil.a
	f77 fracpower.o $(libs) -o fracpower

selectpsfstars: selectpsfstars.o libshape.a libutil.a
	f77 selectpsfstars.o $(libs) -o selectpsfstars
selectpsfstars_auto: selectpsfstars_auto.o libshape.a libutil.a
	f77 selectpsfstars_auto.o $(libs) -o selectpsfstars_auto
psfcat2sh: psfcat2sh.o  libshape.a libutil.a
	f77 psfcat2sh.o $(libs) -o psfcat2sh
fitpsfmap: fitpsfmap.o  libshape.a libutil.a
	f77 fitpsfmap.o $(libs) -o fitpsfmap
fitpsfmap2: fitpsfmap2.o  libshape.a libutil.a
	f77 fitpsfmap2.o $(libs) -o fitpsfmap2
showpsfmap: showpsfmap.o libshape.a libutil.a
	f77 showpsfmap.o $(libs) -o showpsfmap

colplot: colplot.o
	f77 colplot.o $(libs) -o colplot

psf: selectpsfstars selectpsfstars_auto psfcat2sh fitpsfmap showpsfmap

cat2sh: cat2sh.o libshape.a libutil.a
	f77 cat2sh.o $(libs) -o cat2sh
cat2sherr: cat2sherr.o libshape.a libutil.a
	f77 cat2sherr.o $(libs) -o cat2sherr
cat2shcov: cat2shcov.o libshape.a libutil.a
	f77 cat2shcov.o $(libs) -o cat2shcov
sortbybeta: sortbybeta.o libutil.a
	f77 sortbybeta.o $(libs) -o sortbybeta
sh2g: sh2g.o libshape.a libutil.a
	f77 sh2g.o $(libs) -o sh2g
sh2gerr: sh2gerr.o libshape.a libutil.a
	f77 sh2gerr.o $(libs) -o sh2gerr
sh2gerrshift: sh2gerrshift.o libshape.a libutil.a
	f77 sh2gerrshift.o $(libs) -o sh2gerrshift
sh2gerrshift012: sh2gerrshift012.o libshape.a libutil.a
	f77 sh2gerrshift012.o $(libs) -o sh2gerrshift012
sh2gerrshift012diff: sh2gerrshift012diff.o libshape.a libutil.a
	f77 sh2gerrshift012diff.o $(libs) -o sh2gerrshift012diff
sh2gerrshift012max: sh2gerrshift012max.o libshape.a libutil.a
	f77 sh2gerrshift012max.o $(libs) -o sh2gerrshift012max
sh2gerrshift012up: sh2gerrshift012up.o libshape.a libutil.a
	f77 sh2gerrshift012up.o $(libs) -o sh2gerrshift012up
sh2gerrshift012dwn: sh2gerrshift012dwn.o libshape.a libutil.a
	f77 sh2gerrshift012dwn.o $(libs) -o sh2gerrshift012dwn
sh2p: sh2p.o libshape.a libutil.a
	f77 sh2p.o $(libs) -o sh2p
reconstructimage: reconstructimage.o libshape.a libutil.a
	f77 reconstructimage.o $(libs) -o reconstructimage
shearstats: shearstats.o libshape.a libutil.a 
	f77 shearstats.o $(libs) -o shearstats
shearstats2: shearstats2.o libshape.a libutil.a 
	f77 shearstats2.o $(libs) -o shearstats2
shearstats2_ludo: shearstats2_ludo.o libshape.a libutil.a 
	f77 shearstats2_ludo.o $(libs) -o shearstats2_ludo
shearstatsmag: shearstatsmag.o libshape.a libutil.a 
	f77 shearstatsmag.o $(libs) -o shearstatsmag
shearstatsfw: shearstatsfw.o libshape.a libutil.a 
	f77 shearstatsfw.o $(libs) -o shearstatsfw
stackshear: stackshear.o libshape.a libutil.a 
	f77 stackshear.o $(libs) -o  stackshear
showsh: showsh.o libshape.a libutil.a
	f77 showsh.o $(libs) -o showsh

all: psf cat2sh cat2sherr cat2shcov reconstructimage sh2g sh2gerr sh2gerrshift sh2gerrshift012 sh2gerrshift012diff sh2gerrshift012max sh2gerrshift012up sh2gerrshift012dwn sh2p \
         shearstats shearstats2 stackshear showsh fracpower

clean:
	\rm *.o *.a *~ testmain testshear testdecode testmrq testortho testoper testconvolve testround testplot testgaussians testpsfmat testfitshear thetest testreal testfits test012 testsherr testresiduals testsersic selectpsfstars selectpsfstars_auto psfcat2sh fitpsfmap showpsfmap cat2sh cat2sherr cat2shcov reconstructimage sh2g sh2gerr sh2gerrshift sh2gerrshift012 sh2gerrshift012diff sh2gerrshift012max sh2gerrshift012up sh2gerrshift012dwn sh2p shearstats shearstats2 stackshear showsh fracpower fakeimage fakeimage2 fakeimage3 fakeimage4 testcentershape testfitmc testphotmc testresiduals012 testresiduals012conv testresiduals012mc testresiduals012mcnoise


backup:
	tar cfz backupdir/shpl-`date -Iseconds| sed s/://g`.tgz *.F *.csh *.smo Notes makefile* *readme*

towork:
	./tokuinder.csh
fromwork:
	./fromkuinder.csh

tests: testmain testshear testdecode testmrq testortho testoper testconvolve testround testplot testgaussians testpsfmat testfitshear thetest testreal testfits testsherr testcentershape fakeimage fakeimage2 fakeimage3 fakeimage4 test012 testresiduals testresiduals012 testresiduals012conv testresiduals012mc testresiduals012mcnoise testsersic testfitmc testphotmc
