#
#LINUX LIBRARIES
libs = -L. -lshape -lutil -L ~/lib -lpgplot -lcfitsio -lX11 -O
# OLD LIBRARIES:
#FC8
#libs = -L. -lshape -lutil -L ~/lib -lpgplot -lcfitsio -L/usr/X11R6/lib -lX11 -O
#
#libs = -L. -lshape -lutil -L/usr/X11R6/lib -lX11 /home/strw/kuijken/lib/pgplot/libpgplot.a -lcfitsio -O
#libs = -L. -lshape -lutil -L/usr/X11R6/lib -L/usr/lib -lX11 -lpgplot -lpng -lcfitsio -O
#
#
# COMPILER
#
F77 = gfortran
