eemsmakefile:
	cat makefile.eems makefile.common > makefile
bonnmakefile:
	cat makefile.bonn makefile.common > makefile
linuxmakefile:
	cat makefile.linux makefile.common > makefile
macmakefile:
	cat makefile.macos makefile.common > makefile
linuxfc10makefile:
	cat makefile.linuxfc10 makefile.common > makefile

# mm is maximum shapelet order that will be used
# mmpix is maximum size of a fits image that can be analyzed (mmpix x mmpix)
# mmpoly is maximum polynomial order to be used for spatial variation of PSF
#
# Make sure the following derived parameters are consistent with these choices
# msh = (mm+1) * (mm+2) /2 +2
# mmpoly2=(mmpoly+1)*(mmpoly+2)/2
#
flg1 = -Dmm=16 -Dmsh=155 -Dmmpix=9000 -Dmmcat=1000000 -Dmmpoly=6 -Dmmpoly2=28
flg2 = -ffixed-line-length-0 -O -Wall

.F.o: 
	$(F77) $(flg1) $(flg2) -c  -O $*.F


libshape.a: code.o convolve.o fitshear.o operators.o plotshape.o \
            setpsfmat.o setroundshear.o setroundshearshift.o
	ar crs libshape.a code.o convolve.o fitshear.o operators.o plotshape.o\
            setpsfmat.o setroundshear.o setroundshearshift.o
libutil.a: fits.o mrq.o workhorse.o fitpoly.o readpars.o
	ar crs libutil.a fits.o mrq.o workhorse.o fitpoly.o readpars.o

testmain: testmain.o libshape.a libutil.a
	$(F77) testmain.o $(libs) -o testmain
testshear: testshear.o  libshape.a libutil.a
	$(F77) testshear.o $(libs) -o testshear
testsh2gerr: testsh2gerr.o libshape.a libutil.a
	     $(F77) testsh2gerr.o $(libs) -o testsh2gerr
testdecode: testdecode.o  libshape.a libutil.a
	$(F77) testdecode.o $(libs) -o testdecode
testortho: testortho.o  libshape.a libutil.a
	$(F77) testortho.o $(libs) -o testortho
testoper: testoper.o  libshape.a libutil.a
	$(F77) testoper.o $(libs) -o testoper
testconvolve: testconvolve.o  libshape.a libutil.a
	$(F77)  testconvolve.o $(libs) -o testconvolve
testround: testround.o  libshape.a libutil.a
	$(F77) testround.o $(libs) -o testround
testplot: testplot.o  libshape.a libutil.a
	$(F77)  testplot.o $(libs) -o testplot
testgaussians: testgaussians.o  libshape.a libutil.a
	$(F77) testgaussians.o $(libs) -o testgaussians
testmrq: testmrq.o libshape.a libutil.a
	$(F77) testmrq.o $(libs) -o testmrq
testpsfmat: testpsfmat.o  libshape.a libutil.a
	$(F77) testpsfmat.o $(libs) -o testpsfmat
testfitshear: testfitshear.o  libshape.a libutil.a
	$(F77) testfitshear.o $(libs) -o testfitshear
testfitshearmoffat: testfitshearmoffat.o  libshape.a libutil.a
	$(F77) testfitshearmoffat.o $(libs) -o testfitshearmoffat
thetest: thetest.o  libshape.a libutil.a
	$(F77) thetest.o $(libs) -o thetest
testreal: testreal.o  libshape.a libutil.a
	$(F77) testreal.o $(libs) -o testreal
testfits: testfits.o libshape.a libutil.a
	$(F77) testfits.o $(libs) -o testfits
testsherr: testsherr.o libshape.a libutil.a
	$(F77) testsherr.o $(libs) -o testsherr
testcentershape: testcentershape.o libshape.a libutil.a
	$(F77) testcentershape.o $(libs) -o testcentershape
testresiduals: testresiduals.o libshape.a libutil.a
	$(F77) testresiduals.o $(libs) -o testresiduals
testresiduals012: testresiduals012.o libshape.a libutil.a
	$(F77) testresiduals012.o $(libs) -o testresiduals012
testresiduals012_o2: testresiduals012_o2.o libshape.a libutil.a
	$(F77) testresiduals012_o2.o $(libs) -o testresiduals012_o2
testresiduals012conv: testresiduals012conv.o libshape.a libutil.a
	$(F77) testresiduals012conv.o $(libs) -o testresiduals012conv
testresiduals012mcbeta: testresiduals012mcbeta.o libshape.a libutil.a
	$(F77) testresiduals012mcbeta.o $(libs) -o testresiduals012mcbeta
testresiduals012mc: testresiduals012mc.o libshape.a libutil.a
	$(F77) testresiduals012mc.o $(libs) -o testresiduals012mc
testresiduals012_o2_mc: testresiduals012_o2_mc.o libshape.a libutil.a
	$(F77) testresiduals012_o2_mc.o $(libs) -o testresiduals012_o2_mc
testresiduals012_o3_mc: testresiduals012_o3_mc.o libshape.a libutil.a
	$(F77) testresiduals012_o3_mc.o $(libs) -o testresiduals012_o3_mc
testresiduals012mcnoise: testresiduals012mcnoise.o libshape.a libutil.a
	$(F77) testresiduals012mcnoise.o $(libs) -o testresiduals012mcnoise
test012: test012.o libshape.a libutil.a
	$(F77) test012.o  $(libs) -o test012
testfitmc: testfitmc.o libshape.a libutil.a
	$(F77) testfitmc.o $(libs) -o testfitmc 
testphotmc: testphotmc.o libshape.a libutil.a
	$(F77) testphotmc.o $(libs) -o testphotmc 
testsersic: testsersic.o libshape.a libutil.a
	$(F77) testsersic.o  $(libs) -o testsersic
testpsfcorphot: testpsfcorphot.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot.o psfcorphot.o $(libs) -o testpsfcorphot
testpsfcorphot_mc_noise: testpsfcorphot_mc_noise.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_noise.o psfcorphot.o $(libs) -o testpsfcorphot_mc_noise
testpsfcorphot_mc_new: testpsfcorphot_mc_new.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_new.o psfcorphot.o $(libs) -o testpsfcorphot_mc_new
testpsfcorphot_mc_new12: testpsfcorphot_mc_new12.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_new12.o psfcorphot.o $(libs) -o testpsfcorphot_mc_new12
testpsfcorphot_mc_new2: testpsfcorphot_mc_new2.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_new2.o psfcorphot.o $(libs) -o testpsfcorphot_mc_new2
testpsfcorphot_mc_new3: testpsfcorphot_mc_new3.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_new3.o psfcorphot.o $(libs) -o testpsfcorphot_mc_new3
testpsfcorphot_mc_noise_new: testpsfcorphot_mc_noise_new.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_noise_new.o psfcorphot.o $(libs) -o testpsfcorphot_mc_noise_new
testpsfcorphot_mc: testpsfcorphot_mc.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc.o psfcorphot.o $(libs) -o testpsfcorphot_mc
testpsfcorphot_mc_no13: testpsfcorphot_mc_no13.o psfcorphot.o libshape.a libutil.a
	$(F77) testpsfcorphot_mc_no13.o psfcorphot.o $(libs) -o testpsfcorphot_mc_no13
gethighordershearcoefs: gethighordershearcoefs.o round.o libshape.a libutil.a
	$(F77) gethighordershearcoefs.o round.o $(libs) -o gethighordershearcoefs
writehighordershearcoefs: writehighordershearcoefs.o round.o libshape.a libutil.a
	$(F77) writehighordershearcoefs.o round.o $(libs) -o writehighordershearcoefs
listpsfcorphot: listpsfcorphot.o psfcorphot.o libshape.a libutil.a
	$(F77) listpsfcorphot.o psfcorphot.o $(libs) -o listpsfcorphot
listpsfcorphot2: listpsfcorphot2.o psfcorphot.o libshape.a libutil.a
	$(F77) listpsfcorphot2.o psfcorphot.o $(libs) -o listpsfcorphot2
listpsfcorphot3: listpsfcorphot3.o psfcorphot.o libshape.a libutil.a
	$(F77) listpsfcorphot3.o psfcorphot.o $(libs) -o listpsfcorphot3
listpsfcorphot4: listpsfcorphot4.o psfcorphot.o libshape.a libutil.a
	$(F77) listpsfcorphot4.o psfcorphot.o $(libs) -o listpsfcorphot4
listpsfcorphot40: listpsfcorphot40.o psfcorphot.o libshape.a libutil.a
	$(F77) listpsfcorphot40.o psfcorphot.o $(libs) -o listpsfcorphot40
listfitbeta: listfitbeta.o libshape.a libutil.a
	$(F77) listfitbeta.o $(libs) -o listfitbeta
testhighorders: testhighorders.o libshape.a libutil.a
	$(F77) testhighorders.o $(libs) -o testhighorders

fakeimage: fakeimage.o libshape.a libutil.a
	$(F77) fakeimage.o $(libs) -o fakeimage
fakeimage2: fakeimage2.o libshape.a libutil.a
	$(F77) fakeimage2.o $(libs) -o fakeimage2
fakeimage3: fakeimage3.o libshape.a libutil.a
	$(F77) fakeimage3.o $(libs) -o fakeimage3
fakeimage4: fakeimage4.o libshape.a libutil.a
	$(F77) fakeimage4.o $(libs) -o fakeimage4
mcimage: mcimage.o libutil.a
	$(F77) mcimage.o $(libs) -o mcimage
mcimage_ell: mcimage_ell.o libshape.a libutil.a
	$(F77) mcimage_ell.o $(libs) -o mcimage_ell
mcimage_ell_step4: mcimage_ell_step4.o libshape.a libutil.a
	$(F77) mcimage_ell_step4.o $(libs) -o mcimage_ell_step4
mcimage_flx: mcimage_flx.o libshape.a libutil.a
	$(F77) mcimage_flx.o $(libs) -o mcimage_flx
mkimage_flx: mkimage_flx.o libshape.a libutil.a
	$(F77) mkimage_flx.o $(libs) -o mkimage_flx
mkimage_mcg: mkimage_mcg.o libshape.a libutil.a
	$(F77) mkimage_mcg.o $(libs) -o mkimage_mcg
mkimage_mcg_fix: mkimage_mcg_fix.o libshape.a libutil.a
	$(F77) mkimage_mcg_fix.o $(libs) -o mkimage_mcg_fix

fracpower: fracpower.o libshape.a libutil.a
	$(F77) fracpower.o $(libs) -o fracpower
shummary: shummary.o 
	  $(F77) shummary.o -o shummary
selectpsfstars: selectpsfstars.o libshape.a libutil.a
	$(F77) selectpsfstars.o $(libs) -o selectpsfstars
selectpsfstars_auto: selectpsfstars_auto.o libshape.a libutil.a
	$(F77) selectpsfstars_auto.o $(libs) -o selectpsfstars_auto
psfcat2sh: psfcat2sh.o  libshape.a libutil.a
	$(F77) psfcat2sh.o $(libs) -o psfcat2sh
psfcat2sherr: psfcat2sherr.o  libshape.a libutil.a
	$(F77) psfcat2sherr.o $(libs) -o psfcat2sherr
fitpsfmap: fitpsfmap.o  libshape.a libutil.a
	$(F77) fitpsfmap.o $(libs) -o fitpsfmap
fitpsfmap2: fitpsfmap2.o  libshape.a libutil.a
	$(F77) fitpsfmap2.o $(libs) -o fitpsfmap2
showpsfmap: showpsfmap.o libshape.a libutil.a
	$(F77) showpsfmap.o $(libs) -o showpsfmap
showpsfmapcol: showpsfmapcol.o libshape.a libutil.a
	$(F77) showpsfmapcol.o $(libs) -o showpsfmapcol
showpsfmap2: showpsfmap2.o libshape.a libutil.a
	$(F77) showpsfmap2.o $(libs) -o showpsfmap2
psfmap2psf: psfmap2psf.o libshape.a libutil.a
	$(F77) psfmap2psf.o $(libs) -o psfmap2psf
psfmapmingaus: psfmapmingaus.o libshape.a libutil.a
	$(F77) psfmapmingaus.o $(libs) -o psfmapmingaus
psfcoefs: psfcoefs.o libshape.a 
	$(F77) psfcoefs.o $(libs) -o psfcoefs
gaussianizepsf: gaussianizepsf.o  libshape.a libutil.a
	$(F77) gaussianizepsf.o  $(libs) -o gaussianizepsf
gaussianizepsf2: gaussianizepsf2.o  libshape.a libutil.a
	$(F77) gaussianizepsf2.o  $(libs) -o gaussianizepsf2
gaussianizepsf3: gaussianizepsf3.o  libshape.a libutil.a
	$(F77) gaussianizepsf3.o  $(libs) -o gaussianizepsf3
gaussianizepsf4: gaussianizepsf4.o  libshape.a libutil.a
	$(F77) gaussianizepsf4.o  $(libs) -o gaussianizepsf4
gaussianizepsf5: gaussianizepsf5.o  libshape.a libutil.a
	$(F77) gaussianizepsf5.o  $(libs) -o gaussianizepsf5
checkkernel: checkkernel.o libshape.a libutil.a
	$(F77) checkkernel.o $(libs) -o checkkernel
imxshmap: imxshmap.o libshape.a libutil.a
	$(F77) imxshmap.o $(libs) -o imxshmap

colplot: colplot.o
	$(F77) colplot.o $(libs) -o colplot

psf: selectpsfstars selectpsfstars_auto psfcat2sh psfcat2sherr fitpsfmap showpsfmap showpsfmap2

cat2sh: cat2sh.o libshape.a libutil.a
	$(F77) cat2sh.o $(libs) -o cat2sh
cat2sherr: cat2sherr.o libshape.a libutil.a
	$(F77) cat2sherr.o $(libs) -o cat2sherr
cat2shcov: cat2shcov.o libshape.a libutil.a
	$(F77) cat2shcov.o $(libs) -o cat2shcov
sortbybeta: sortbybeta.o libutil.a
	$(F77) sortbybeta.o $(libs) -o sortbybeta
listbeta: listbeta.o libutil.a
	$(F77) listbeta.o $(libs) -o listbeta
sh2g: sh2g.o libshape.a libutil.a
	$(F77) sh2g.o $(libs) -o sh2g
sh2gerr: sh2gerr.o libshape.a libutil.a
	$(F77) sh2gerr.o $(libs) -o sh2gerr
sh2gerrshift: sh2gerrshift.o libshape.a libutil.a
	$(F77) sh2gerrshift.o $(libs) -o sh2gerrshift
sh2gerrshift012_o4: sh2gerrshift012_o4.o libshape.a libutil.a
	$(F77) sh2gerrshift012_o4.o $(libs) -o sh2gerrshift012_o4
sh2gerrshift_o4: sh2gerrshift_o4.o libshape.a libutil.a
	$(F77) sh2gerrshift_o4.o $(libs) -o sh2gerrshift_o4
sh2gerrshift012: sh2gerrshift012.o libshape.a libutil.a
	$(F77) sh2gerrshift012.o $(libs) -o sh2gerrshift012
sh2p: sh2p.o libshape.a libutil.a
	$(F77) sh2p.o $(libs) -o sh2p
reconstructimage: reconstructimage.o libshape.a libutil.a
	$(F77) reconstructimage.o $(libs) -o reconstructimage
shearstats: shearstats.o libshape.a libutil.a 
	$(F77) shearstats.o $(libs) -o shearstats
shearstats2: shearstats2.o libshape.a libutil.a 
	$(F77) shearstats2.o $(libs) -o shearstats2
shearstats2_ludo: shearstats2_ludo.o libshape.a libutil.a 
	$(F77) shearstats2_ludo.o $(libs) -o shearstats2_ludo
shearstatsmag: shearstatsmag.o libshape.a libutil.a 
	$(F77) shearstatsmag.o $(libs) -o shearstatsmag
shearstatsfw: shearstatsfw.o libshape.a libutil.a 
	$(F77) shearstatsfw.o $(libs) -o shearstatsfw
stackshear: stackshear.o libshape.a libutil.a 
	$(F77) stackshear.o $(libs) -o  stackshear
showsh: showsh.o libshape.a libutil.a
	$(F77) showsh.o $(libs) -o showsh
symmetrizepsfmap: symmetrizepsfmap.o 
	$(F77) symmetrizepsfmap.o $(libs) -o symmetrizepsfmap

all: psf cat2sh cat2sherr cat2shcov reconstructimage sh2g sh2gerr sh2gerrshift sh2gerrshift012 sh2gerrshift_o4 sh2p \
         shearstats shearstats2 stackshear showsh fracpower sortbybeta listpsfcorphot40 listfitbeta

clean:
	\rm *.o *.a *~ testmain testshear testdecode testmrq testortho testoper testconvolve testround testplot testgaussians testpsfmat testfitshear thetest testreal testfits test012 testsherr testresiduals testsersic selectpsfstars selectpsfstars_auto psfcat2sh fitpsfmap showpsfmap cat2sh cat2sherr cat2shcov reconstructimage sh2g sh2gerr sh2gerrshift sh2gerrshift_o4 sh2gerrshift012 sh2p shearstats shearstats2 stackshear showsh fracpower fakeimage fakeimage2 fakeimage3 fakeimage4 testcentershape testfitmc testphotmc testresiduals012 testresiduals012conv testresiduals012mc testresiduals012mcnoise sortbybeta listpsfcorphot40 psfcat2sherr listfitbeta gethighordershearcoefs writehighordershearcoefs listbeta


backup:
	tar cfz backupdir/shpl-`date -Iseconds| sed s/://g`.tgz *.F *.csh *.smo Notes makefile* *readme* 

towork:
	./tokuinder.csh
fromwork:
	./fromkuinder.csh

tests: testmain testshear testdecode testmrq testortho testoper testconvolve testround testplot testgaussians testpsfmat testfitshear thetest testreal testfits testsherr testcentershape fakeimage fakeimage2 fakeimage3 fakeimage4 test012 testresiduals testresiduals012 testresiduals012conv testresiduals012mc testresiduals012mcnoise testsersic testfitmc testphotmc
